repos:
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length", "120"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E203
        files: \.py$
        exclude: .venv/|alembic/|

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort
        args:
        - --profile
        - black
        - --line-length
        - '120'
        files: \.py$

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 1.15.0
  #   hooks:
  #     - id: mypy
  #       args:
  #         - --ignore-missing-imports
  #         - --disallow-untyped-calls
  #         - --disallow-untyped-decorators
  #         - --config-file=pyproject.toml

  #       files: \.py$
  #       exclude: .venv|migrations/|__init__.py
